# Python Fundamentals for Data Science
This notebook introduces the **basic Python concepts and actions** needed to prepare for Mod 1 and Mod 2. Each section has explanations followed by examples.

## 1. Variables, Types, and Expressions
In Python, you can assign values to variables and perform arithmetic operations easily.

### Concepts:
- **Variables** are names that store values.
- **Types**: Python supports `int`, `float`, `str`, and `bool`.

  ####  Common data types:
  - `int`: integer (e.g. `5`)
  - `float`: floating point number (e.g. `3.14`)
  - `str`: string of characters (e.g. `"hello"`, `"123"`)
  - `bool`: boolean (`True` or `False`)

You can check the type with `type()`.
- Use `type()` to check the data type.

In [1]:
# Declare variables of different types
a = 10
b = 3.14
name = "Data Science"
is_student = True

# Check types
print(type(a))         # int
print(type(b))         # float
print(type(name))      # str
print(type(is_student))# bool

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

#### Assignment statements

Values are assigned to variables with the assignment statement (=). An assignment statement may have a constant or an expression on the right hand side of the (=) sign, and a variable name on the left hand side.

In [2]:
# Reassignment
age = 25
age = age + 1           # now age is 26
print("Updated age:", age)

Updated age: 26

### Practice exercise

What is the datatype of the following objects?

1. ‘This is False’

2. “This is a number”

3. 1000

4. 65.65

5. False

In [3]:
print(type('This is False'))
print(type("This is a number"))
print(type(1000))
print(type(65.65))
print(type(False))

<class 'str'>
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

### 1.1 Variable names

There are a some rules for naming variables:

1. A variable name must start with a letter or underscore _

2. A variable name may consist of letters, numbers, and underscores only

For example, some of the valid variable names are `salary`, `text10`, `_varname`. Some of the invalid variable names are `salary%`, `10text`.

3. Variable names are case-sensitive. For example, the variable `My_var` will be different from `my_var`.

4. There are certain *reserved* words in python that have some meaning, and cannot be used as variable names.

| and     | as     | assert  | break   | class   | continue |
|---------|--------|---------|---------|---------|----------|
| def     | del    | elif    | else    | except  | exec     |
| finally | for    | from    | global  | if      | import   |
| in      | is     | lambda  | nonlocal| not     | or       |
| pass    | raise  | return  | try     | while   | with     |
| yield   | True   | False   | None    |         |          |

Variables should be named such that they are informative of the value they are storing. For example, suppose we wish to compute the income tax a person has to pay based on their income and tax rate. Below are two ways of naming variables to do this computation

In [4]:
income = 80000
tax_rate = 0.15
print("Income tax = ", income*tax_rate)

Income tax =  12000.0

In [5]:
a = 80000
b = 0.15
print("Income tax = ",a*b)

Income tax =  12000.0

### Practice exercise

#### Valid variable names?

Which of the following variable names are valid?

1. var.name

2. var9name

3. _varname

4. varname*

In [7]:
print("var.name".isidentifier())
print("var9name".isidentifier())
print("_varname".isidentifier())
print("varname*".isidentifier())

False
True
True
False

##  2. Basic Arithmetic and Logic
###  Concepts:
#### Math Operators
- `+`, `-`, `*`, `/` — basic arithmetic
- `**` — exponent
- `//` — floor division
- `%` — modulo (remainder)




**What is Floor Division (//)?**

Floor division divides two numbers and rounds the result down to the nearest whole number. It tells you how many full times one number fits into another.

Example:
- 135 // 60 = 2
- 17 // 5 = 3


**What is Modulo (%)?**

Modulo returns the remainder after division. It's useful for finding what's left over.

Example:
- 135 % 60 = 15
- 17 % 5 = 2

In [8]:
# Arithmetic
x = 8
y = 3

# Last evaluation
print("Addition:", x + y)
print("Subtraction:", x - y)

# middle evaluation
print("Multiplication:", x * y)
print("Division:", x / y)
print("Floor Division:", x // y)
print("Modulo:", x % y)

# First evaluation
print("Exponentiation:", x ** y)

Addition: 11
Subtraction: 5
Multiplication: 24
Division: 2.6666666666666665
Floor Division: 2
Modulo: 2
Exponentiation: 512

The operators above are in decreasing order of precedence, i.e., an exponent will be evaluated before a remainder, a remainder will be evaluated before a addition. Within groups the same level of precendence (multiplication and division) they are evaluated from left to right.

For example, check the precedence of operators in the computation of the following expression:

In [9]:
2+3%4*2

8

In case an expression becomes too complicated, use of parenthesis may help clarify the precedence of operators. Parenthesis takes precedence over all the operators listed above. For example, in the expression below, the terms within parenthesis are evaluated first:

In [10]:
2+3%(4*2)

5

### Practice exercise

Which of the following statements is an assignment statement:

1. x = 5

2. print(x)

3. type(x)

4. x + 4

What will be the result of the following expression:



```
1%2**3*2+1
```

In [11]:
1%2**3*2+1

3

## 3. Comparing Formulas and Checking Inequality
###  Concept:
Assign results of expressions to variables, then compare.

###  Why compare formulas?
In data analysis, we often want to **compare values or results** of different formulas.


For testing if conditions are true or false, first we need to learn the operators that can be used for comparison. For example, suppose we want to check if two objects are equal, we use the `==` operator:

| Python Code | Meaning                               |
|-------------|----------------------------------------|
| `x == y`    | Produces `True` if **x is equal to y** |
| `x != y`    | Produces `True` if **x is not equal to y** |
| `x > y`     | Produces `True` if **x is greater than y** |
| `x < y`     | Produces `True` if **x is less than y** |
| `x >= y`    | Produces `True` if **x is greater than or equal to y** |
| `x <= y`    | Produces `True` if **x is less than or equal to y** |

**Exercise:** Predict the outcome of each of the following print statements. Then check your guess.

In [12]:
a = 7
b = 10

print("a > b:", a > b)
print("a <= b:", a <= b)
print("a != b:", a != b) # not equal
print("a == b:", a == b) # equal

a > b: False
a <= b: True
a != b: True
a == b: False

More examples of complicated expressions.

In [13]:
# Compare two expressions
expr1 = 3 * (4 + 2)
expr2 = 18

print("Are the two expressions equal?", expr1 == expr2)
print("Is expr1 greater than 15?", expr1 > 15)

Are the two expressions equal? True
Is expr1 greater than 15? True

In [14]:
# Compare complex expressions
x = 10
formula1 = x**2 + 2*x + 1     # 121
formula2 = (x + 1)**2         # 121

print("Do the formulas match?", formula1 == formula2)

Do the formulas match? True

### 3.1 Logical operators

Sometimes we may need to check multiple conditions simultaneously. The logical operator `and` is used to check if all the conditions are true, while the logical operator `or` is used to check if either of the conditons is true.

In [15]:
# Checking if both the conditions are true using 'and'
5 == 5 and 67 == 68

False

In [16]:
# Checking if either condition is true using 'or'
x = 6; y = 90
x < 0 or y > 50

True

## 4. Converting Strings to Numbers
###  Concept:
Use `int()` or `float()` to convert strings to numbers.

### Why convert types?
Sometimes data comes as text (like from a file) and needs to be **converted** before calculations.

- `int()` converts to integer  
- `float()` converts to floating point number

In [17]:
# Convert string to number
str_int = "42"
str_float = "3.1415"

num1 = int(str_int)
num2 = float(str_float)

print("String to int:", num1 + 10)
print("String to float:", num2 * 2)

String to int: 52
String to float: 6.283

In [18]:
str_int + 10

TypeError: can only concatenate str (not "int") to str

Sometimes, conversion of a value may not be possible. For example, it is not possible to convert the variable `greeting` defined below to a number:

In [19]:
greeting = "hello"

In [20]:
int(greeting)

ValueError: invalid literal for int() with base 10: 'hello'

In [ ]:
# Catching conversion errors
bad_str = "hello"
try:
    print(int(bad_str))
except ValueError:
    print("Cannot convert to int:", bad_str)

However, in some cases, mathematical operators such as + and * can be applied on strings. The operator + concatenates multiple strings, while the operator * can be used to concatenate a string to itself multiple times:

In [21]:
"Hi" + " there!"

'Hi there!'

In [22]:
"5" + '3'

'53'

In [23]:
"5"*8

'55555555'

##  5. Conditional Logic: `if`, `elif`, `else`
###  Concept:
Run different blocks of code depending on conditions.

### What is conditional logic?
Use it to make decisions:

```python
if condition:
    do_something()
elif other_condition:
    do_another_thing()
else:
    do_fallback()
```

The if-elif-else statements can check several conditions, and execute the code corresponding to the condition that is true. Note that there can be as many elif statements as required.

Syntax: Python uses indentation to identify the code to be executed if a condition is true. All the code indented within a condition is executed if the condition is true.

Example: Input an integer. Print whether it is positive or negative.

In [25]:
number = 5 #Input an integer
number_integer = int(number)       #Convert the integer to 'int' datatype
if number_integer > 0:               #Check if the integer is positive
    print("Number is positive")
else:
    print("Number is negative")

Number is positive

In [ ]:
score = 85

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
else:
    print("Grade: C or below")

In [27]:
# Nested example
age = 10
has_id = True

if age >= 18:
    if has_id:
        print("Entry allowed.")
    else:
        print("Bring ID next time.")
else:
    print("Too young to enter.")

Too young to enter.

### Practice exercise

Print whether its odd or even.

In [28]:
num = int(input("Enter a number: "))
if num%2 == 0:           #Checking if the number is divisible by 2
    print("Number is even")
else:
    print("Number is odd")

Enter a number: 7
Number is odd

note the `input()` command. It will be useful later!

### Practice exercise

Nested if-elif-else statements:
This question will lead you to create nested if statements, i.e., an if statement within another if statement.

Think of a number in [1,5]. Ask the user to guess the number.

- If the user guesses the number correctly, print “Correct in the first attempt!”, and stop the program. Otherwise, print “Incorrect! Try again” and give them another chance to guess the number.
- If the user guesses the number correctly in the second attempt, print “Correct in the second attempt”, otherwise print “Incorrect in both the attempts, the correct number is:”, and print the correct number.

In [ ]:
#Let us say we think of the number. Now the user has to guess the number in two attempts.
rand_no = 3
guess = input("Guess the number:")
if int(guess)==rand_no:
    print("Correct in the first attempt!")

#If the guess is incorrect, the program will execute the code block below
else:
    guess = input("Incorrect! Try again:")
    if int(guess) == rand_no:
        print("Correct in the second attempt")
    else:
        print("Incorrect in the both the attempts, the correct number was:", rand_no)

### 5.1 Try-except

If we suspect that some lines of code may produce an error, we can put them in a `try` block, and if an error does occur, we can use the `except` block to instead execute an alternative piece of code. This way the program will not stop if an error occurs within the `try` block, and instead will be directed to execute the code within the `except` block.

**Example**: Input an integer from the user. If the user inputs a valid integer, print whether it is a multiple of 3. However, if the user does not input a valid integer, print a message saying that the input is invalid.

In [30]:
num = input("Enter an integer:")

#The code lines within the 'try' block will execute as long as they run without error
try:
    #Converting the input to integer, as user input is a string
    num_int = int(num)

    #checking if the integer is a multiple of 3
    if num_int % 3 == 0:
        print("Number is a multiple of 3")
    else:
        print("Number is not a multiple of 3")

#The code lines within the 'except' block will execute only if the code lines within the 'try' block throw an error
except:
    print("Input must be an integer")

Enter an integer:9
Number is a multiple of 3

##  6. Loops

### 6.1 `for` loop
**Concept:**
Loop over elements in a list or use `range()` to iterate a number of times.

We typically use `for` loops with an in-built python function called `range()` that supports `for` loops. Below is its description.

**range()**: The `range()` function creates an iterative object that represents an immutable sequence of numbers and is commonly used for looping a specific number of times in for loops.

The advantage of the range type over a regular list or tuple is that a range object will always take the same (small) amount of memory, no matter the size of the range it represents (as it only stores the start, stop and step values, calculating individual items and subranges as needed).

In [34]:
for i in range(10,0, -3):
    print("Number:", i)

Number: 10
Number: 7
Number: 4
Number: 1

In [36]:
numbers = [10, 20, 30]
total = 0
for num in numbers:
    total += num
print("Total:", total)

Total: 10
Total: 30
Total: 60

In [37]:
# Loop through a list
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print("I like", fruit)

I like apple
I like banana
I like cherry

In [38]:
# Calculate sum using a loop
numbers = [4, 7, 2, 9, 5]
total = 0
for num in numbers:
    total += num
print("Total:", total)

Total: 27

### 6.2 `while` loop

With a `while` loops, a piece of code is executed repeatedly until certain condition(s) hold.

Example: Print all the elements of the [Fibonacci sequence](https://en.wikipedia.org/wiki/Fibonacci_sequence) less than n, where n is an integer input by the user, such that n>2. In a fibonacci sequence, each number is the sum of the preceding two numbers, and the sequence starts from 0,1. The sequence is as follows:

0,1,1,2,3,5,8,13,….

In [39]:
n = int(input("Enter the value of n:"))

#Initializing the sequence to start from 0, 1
n1 = 0; n2 = 1

#Printing the first number of the sequence
print(n1)

while n2 < n:

    #Print the next number of the sequence
    print(n2)

    #Comptuing the next number of the sequence as the summation of the previous two numbers
    n3 = n1 + n2

    #As n2 is already printed, assigning n2 to n3, so that the next number of the sequence (i.e., currently n3) is printed
    #if the program enters the loop again
    #Assigning n1 to n2 as n1 has already been used to compute the next number of the seqeunce (i.e., currently n3).
    n1 = n2
    n2 = n3
print("These are all the elements of the fibonacci series less than", n)

Enter the value of n:5
0
1
1
2
3
These are all the elements of the fibonacci series less than 5

### Practice exercise

Write a program that checks whether a number entered by the user is a **prime number**.

A **prime number** is a number greater than 1 that has no divisors other than 1 and itself.

**Example**:
- `2`, `3`, `5`, `7` are prime
- `4`, `6`, `8`, `9` are not

**Your Task**:
Prompt the user to enter a number, and then print whether it's prime.

**Hint**:
- Use a `for` loop to check if the number is divisible by any number between `2` and `n-1`.
- If you find a divisor, it’s not a prime.
- You can **break the loop early** when a divisor is found.

In [ ]:
number = int(input("Enter a positive integer:"))

#Defining a variable that will have a value of 0 if there are no divisors
num_divisors = 0

#Checking if the number has any divisors from 2 to half of the number
for divisor in range(2,int(number ** 0.5) + 1):
        if number % divisor == 0:

            #If the number has a divisor, setting num_divisors to 1, to indicate that the number is not prime
            num_divisors = 1

            #If a divisor has been found, there is no need to check if the number has more divisors.
            #Even if the number has a single divisor, it is not prime. Thus, we 'break' out of the loop that checks for divisors
            #If you don't 'break', your code will still be correct, it will just do some unnecessary computations
            break

#If there are no divisors of the number, it is prime, else not prime
if num_divisors == 0:
    print("Prime")
else:
    print("Not prime")

## 7. Data structures

### 7.1 Tuple

Tuple is a sequence of python objects, with two key characeterisics: (1) the number of objects are fixed, and (2) the objects are immutable, i.e., they cannot be changed.

Tuple can be defined as a sequence of python objects separated by commas, and enclosed in rounded brackets (). For example, below is a tuple containing three integers.

In [40]:
tuple_example = (2,7,4)

Tuple can be defined without the rounded brackets as well

In [41]:
tuple_example = 2, 7, 4

We can check the data type of a python object using the type() function. Let us check the data type of the object `tuple_example`.

In [42]:
type(tuple_example)

tuple

Elements of a tuple can be extracted using their index within square brackets. For example the second element of the tuple `tuple_example` can be extracted as follows

In [43]:
tuple_example[1]

7

Note that an element of a tuple cannot be modified. For example, consider the following attempt in changing the second element of the tuple `tuple_example`.

In [44]:
tuple_example[1] = 8

TypeError: 'tuple' object does not support item assignment

The above code results in an error as tuple elements cannot be modified.

### Practice exercise

USA’s GDP per capita from 1960 to 2021 is given by the tuple T in the code cell below. The values are arranged in ascending order of the year, i.e., the first value is for 1960, the second value is for 1961, and so on. Print the years in which the GDP per capita of the US increased by more than 10%.

In [ ]:
T = (3007, 3067, 3244, 3375,3574, 3828, 4146, 4336, 4696, 5032,5234,5609,6094,6726,7226,7801,8592,9453,10565,
     11674,12575,13976,14434,15544,17121,18237,19071,20039,21417,22857,23889,24342,25419,26387,27695,28691,29968,
     31459,32854,34515,36330,37134,37998,39490,41725,44123,46302,48050,48570,47195,48651,50066,51784,53291,55124,
     56763,57867,59915,62805,65095,63028,69288)

In [ ]:
#Iterating over each element of the tuple
for i in range(len(T)-1):

    #Computing percentage increase in GDP per capita in the (i+1)th year
    increase = (T[i+1]-T[i])/T[i]

    #Printing the year if the increase in GDP per capita is more than 10%
    if increase>0.1:
        print(i+1961)

#### 7.1.1 Concatenating tuples

Tuples can be concatenated using the + operator to produce a longer tuple

In [45]:
(2,7,4) + ("another", "tuple") + ("mixed","datatypes",5)

(2, 7, 4, 'another', 'tuple', 'mixed', 'datatypes', 5)

Multiplying a tuple by an integer results in repetition of the tuple

In [46]:
(2,7,"hi") * 3

(2, 7, 'hi', 2, 7, 'hi', 2, 7, 'hi')

#### 7.1.2 Unpacking tuples

If tuples are assigned to an expression containing multiple variables, the tuple will be unpacked and each variable will be assigned a value as per the order in which it appears. See the example below.

In [47]:
x,y,z  = (4.5, "this is a string", (("Nested tuple",5)))

In [48]:
x

4.5

In [49]:
y

'this is a string'

In [50]:
z

('Nested tuple', 5)

In [51]:
z1, z2=z

In [52]:
z2

5

If we are interested in retrieving only some values of the tuple, the expression *_ can be used to discard the other values. Let’s say we are interested in retrieving only the first and the last two values of the tuple

In [53]:
x,*_,y,z  = (4.5, "this is a string", (("Nested tuple",5)),"99",99)

In [54]:
x

4.5

In [55]:
y

'99'

In [56]:
z

99

#### 7.1.3 Tuple methods

A couple of useful tuple methods are `count`, which counts the occurences of an element in the tuple and `index`, which returns the position of the first occurance of an element in the tuple

In [57]:
tuple_example = (2,5,64,7,2,2)

In [58]:
tuple_example.count(2)

3

In [59]:
tuple_example.index(2)

0

### Practice exercise

For which of the following purposes will it be appropriate to use a tuple: (a) storing mean co-ordinates of a city, (b) storing the maximum temperature and humidity of a city, everyday?

1. both (a) and (b)
2. (a)
3. (b)
4. None

### 7.2 List

List is a sequence of python objects, with two key characeterisics that differentiates it from tuple: (1) the number of objects are variable, i.e., objects can be added or removed from a list, and (2) the objects are mutable, i.e., they can be changed.

List can be defined as a sequence of python objects separated by commas, and enclosed in square brackets []. For example, below is a list consisting of three integers.

In [60]:
list_example = [2,7,4]

In [61]:
len(list_example)

3

#### Adding and removing elements in a list
We can add elements at the end of the list using the append method. For example, we append the string `red` to the list `list_example` below.

In [62]:
list_example.append('red')

In [63]:
list_example

[2, 7, 4, 'red']

Note that the objects of a list or a tuple can be of different datatypes.

An element can be added at a specific location of the list using the insert method. For example, if we wish to insert the number 2.32 as the second element of the list `list_example`, we can do it as follow

In [64]:
list_example.insert(1, 2.32)

In [65]:
list_example

[2, 2.32, 7, 4, 'red']

For removing an element from the list, the pop and remove methods may be used. The pop method removes an element at a particular index, while the remove method removes the element’s first occurence in the list by its value. See the examples below.

Let us say, we need to remove the third element of the list.

In [66]:
list_example.pop(2)

7

In [67]:
list_example

[2, 2.32, 4, 'red']

Let us say, we need to remove the element ‘red’.

In [68]:
list_example.remove('red')

In [69]:
list_example

[2, 2.32, 4]

If there are multiple occurences of an element in the list, the first occurence will be removed

In [70]:
list_example2 = [2,3,2,4,4]
list_example2.remove(2)
list_example2

[3, 2, 4, 4]

For removing multiple elements in a list, either `pop` or `remove` can be used in a `for` loop, or a `for` loop can be used with a condition. See the examples below.

Let’s say we need to remove integers less than 100 from the following list.

In [ ]:
list_example3 = list(range(95,106))
list_example3

In [ ]:
#Method 1: For loop with remove
list_example3_filtered = list(list_example3) #
for element in list_example3:
    if element<100:
        list_example3_filtered.remove(element)
print(list_example3_filtered)

In [ ]:
#Method 2: Check this method after reading Section 5.2.6 on slicing a list
list_example3 = list(range(95,106))

#Slicing a list using ':' creates a copy of the list, and so
for element in list_example3[:]:
    if element<100:
        list_example3.remove(element)
print(list_example3)

In [ ]:
#Method 3: List comprehension with condition
[element for element in list_example3 if element>100]

#### 7.2.1 List comprehensions
List comprehension is a compact way to create new lists based on elements of an existing list or other objects.

**Example:** Create a list that has squares of natural numbers from 5 to 15.

In [71]:
sqrt_natural_no_5_15 = [(x**2) for x in range(5,16)]
print(sqrt_natural_no_5_15)

[25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225]

**Example:** Create a list of tuples, where each tuple consists of a natural number and its square, for natural numbers ranging from 5 to 15.

In [72]:
sqrt_natural_no_5_15 = [(x, x**2) for x in range(5,16)]
print(sqrt_natural_no_5_15)

[(5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100), (11, 121), (12, 144), (13, 169), (14, 196), (15, 225)]

#### 7.2.2 Concatenating lists
As in tuples, lists can be concatenated using the + operator

In [73]:
list_example4 = [5,'hi',4]
list_example5 = list_example4 + [None,'7',9]
list_example5

[5, 'hi', 4, None, '7', 9]

In [74]:
list_example4

[5, 'hi', 4]

For adding elements to a list, the `extend` method is preferred over the `+` operator. This is because the `+` operator creates a new list, while the `extend` method adds elements to an existing list. Thus, the `extend` operator is more memory efficient.

In [75]:
list_example4 = [5,'hi',4]
list_example4.extend([None, '7', 9])
list_example4

[5, 'hi', 4, None, '7', 9]

#### 7.2.3 Sorting a list

A list can be sorted using the `sort` method

In [76]:
list_example5 = [6,78,9]
list_example5.sort(reverse=True) #the reverse argument is used to specify if the sorting is in ascending or descending order
list_example5

[78, 9, 6]

#### 7.2.4 Slicing a list

We may extract or update a section of the list by passing the starting index (say `start`) and the stopping index (say `stop`) as `start:stop` to the index operator []. This is called slicing a list. For example, see the following example

In [77]:
list_example6 = [4,7,3,5,7,1,5,87,5]

Let us extract a slice containing all the elements from the the 3rd position to the 7th position.

In [78]:
list_example6[2:7]

[3, 5, 7, 1, 5]

Note that while the element at the `start` index is included, the element with the `stop` index is excluded in the above slice.

If either the `start` or `stop` index is not mentioned, the slicing will be done from the beginning or until the end of the list, respectively.

In [79]:
list_example6[:7]

[4, 7, 3, 5, 7, 1, 5]

In [80]:
list_example6[2:]

[3, 5, 7, 1, 5, 87, 5]

To slice the list relative to the end, we can use negative indices

In [81]:
list_example6[-4:]

[1, 5, 87, 5]

In [82]:
list_example6[-4:-2]

[1, 5]

An extra colon (‘:’) can be used to slice every ith element of a list.

In [83]:
#Selecting every 3rd element of a list
list_example6[::3]

[4, 5, 5]

In [84]:
#Selecting every 3rd element of a list from the end
list_example6[::-3]

[5, 1, 3]

In [85]:
#Selecting every element of a list from the end or reversing a list
list_example6[::-1]

[5, 87, 5, 1, 7, 5, 3, 7, 4]

### Practice exercise

Start with the list [8,9,10]. Do the following:

1. Set the second entry (index 1) to 17
2. Add 4, 5, and 6 to the end of the list
3. Remove the first entry from the list
4. Sort the list
5. Double the list (concatenate the list to itself)
6. Insert 25 at index 3

The final list should equal [4,5,6,25,10,17,4,5,6,10,17]

In [ ]:
### Your code here
L = [8,9,10]
L[1]=17
L = L+[4,5,6]
L.pop(0)
L.sort()
L=L+L
L.insert(3,25)
L

### Practice exercise

For which of the following purposes will it be appropriate to use a list: (a) storing the names of all countries, (b) storing the population of all countries each year?

1. both (a) and (b)
2. (a)
3. (b)
4. None

### 7.3 Set

A **set** is a built-in Python data structure that stores **unordered, unique elements**. Sets are useful when you want to store a collection of items **without duplicates** and **don't care about order**.

Sets are defined using the `set()` constructor or with **curly braces `{}`**. However, an empty set must be created with `set()`, not `{}`, because `{}` creates a dictionary by default.

In [86]:
### Example: Creating a Set
### Duplicate values will be ignored
my_set = {'apple', 'banana', 'cherry', 'apple'}
print(my_set)

{'apple', 'banana', 'cherry'}

In [87]:
### True and 1 is considered the same value
my_set = {"apple", "banana", "cherry", True, 1, 2}

print(my_set)

{'apple', True, 2, 'banana', 'cherry'}

A set can contain different data types

In [88]:
### Example

set1 = {"abc", 34, True, 40, "male"}

#### 7.3.1 Adding and Removing Elements in a Set

You can add elements using the `.add()` method, and remove them using `.remove()` or `.discard()`.

In [89]:
my_set.add('orange')
print(my_set)

{'apple', True, 2, 'banana', 'cherry', 'orange'}

In [90]:
my_set.remove('banana')   # Raises error if not found
my_set.discard('grape')   # No error if not found
print(my_set)

{'apple', True, 2, 'cherry', 'orange'}

### 7.4 Dictionary

A dictionary consists of key-value pairs, where the keys and values are python objects. While values can be any python object, keys need to be immutable python objects, like strings, integers, tuples, etc. Thus, a list can be a value, but not a key, as elements of list can be changed. A dictionary is defined using the keyword `dict` along with curly braces, colons to separate keys and values, and commas to separate elements of a dictionary

In [91]:
dict_example = {'USA':'Joe Biden', 'India':'Narendra Modi', 'China':'Xi Jinping'}

Elements of a dictionary can be retrieved by using the corresponding key.

In [92]:
dict_example['USA']

'Joe Biden'

#### 7.4.1 Adding and removing elements in a dictionary

New elements can be added to a dictionary by defining a key in square brackets and assiging it to a value

In [93]:
dict_example['Japan'] = 'Fumio Kishida'
dict_example['Countries'] = 4
dict_example

{'USA': 'Joe Biden',
 'India': 'Narendra Modi',
 'China': 'Xi Jinping',
 'Japan': 'Fumio Kishida',
 'Countries': 4}

Elements can be removed from the dictionary using the `del` method or the `pop` method

In [94]:
#Removing the element having key as 'Countries'
del dict_example['Countries']

In [95]:
dict_example

{'USA': 'Joe Biden',
 'India': 'Narendra Modi',
 'China': 'Xi Jinping',
 'Japan': 'Fumio Kishida'}

In [96]:
#Removing the element having key as 'USA'
dict_example.pop('USA')

'Joe Biden'

In [97]:
dict_example

{'India': 'Narendra Modi', 'China': 'Xi Jinping', 'Japan': 'Fumio Kishida'}

#### 7.4.2 Iterating over elements of a dictionary

The `items()` attribute of a dictionary can be used to iterate over elements of a dictionary

In [98]:
for key,value in dict_example.items():
    print("The Head of State of",key,"is",value)

The Head of State of India is Narendra Modi
The Head of State of China is Xi Jinping
The Head of State of Japan is Fumio Kishida

In [100]:
for key in dict_example.values():
    print(key)

Narendra Modi
Xi Jinping
Fumio Kishida

#### 7.4.3 Checking the dictinary keys

The `.get()` method in Python returns the **value associated with a key**, or `None` if the key **does not exist**.

This makes it useful for **safely checking** whether a key is present.

In [101]:
### Example

leaders = {
    'USA': 'Joe Biden',
    'India': 'Narendra Modi',
    'China': 'Xi Jinping'
}

# Check if 'Japan' is in the dictionary
if leaders.get('Japan') is None:
    print("Key 'Japan' is NOT in the dictionary.")
else:
    print("Key 'Japan' exists.")

Key 'Japan' is NOT in the dictionary.

Why use `get()` instead of `[]`?

Using square brackets like `leaders['Japan']` will raise a `KeyError` if `'Japan'` doesn't exist.
Using `get('Japan')` avoids errors and returns None by default if the key is missing.

In [102]:
# This would cause an error:
print(leaders['Japan'])  # KeyError

KeyError: 'Japan'

In [103]:
# But this is safe:
print(leaders.get('Japan'))  # Output: None

None

### Practice exercise

The object `deck` defined below corresponds to a deck of cards. Estimate the probablity that a five card hand will be a flush, as follows:

1. Write a function that accepts a hand of 5 cards as argument, and returns whether the hand is a flush or not.
2. Randomly pull a hand of 5 cards from the deck. Call the function developed in (1) to determine if the hand is a flush.
3. Repeat (2) 10,000 times.
4. Estimate the probability of the hand being a flush from the results of the 10,000 simulations.

You may use the function `shuffle()` from the `random` library to shuffle the deck everytime before pulling a hand of 5 cards.

In [ ]:
deck = [{'value':i, 'suit':c}
for c in ['spades', 'clubs', 'hearts', 'diamonds']
for i in range(2,15)]

### Your code here

In [ ]:
import random as rm

#Function to check if a 5-card hand is a flush
def chck_flush(hands):

    #Assuming that the hand is a flush, before checking the cards
    yes_flush =1

    #Storing the suit of the first card in 'first_suit'
    first_suit = hands[0]['suit']

    #Iterating over the remaining 4 cards of the hand
    for j in range(1,len(hands)):

        #If the suit of any of the cards does not match the suit of the first card, the hand is not a flush
        if first_suit!=hands[j]['suit']:
            yes_flush = 0;

            #As soon as a card with a different suit is found, the hand is not a flush and there is no need to check other cards. So, we 'break' out of the loop
            break;
    return yes_flush

flush=0
for i in range(10000):

    #Shuffling the deck
    rm.shuffle(deck)

    #Picking out the first 5 cards of the deck as a hand and checking if they are a flush
    #If the hand is a flush it is counted
    flush=flush+chck_flush(deck[0:5])

print("Probability of obtaining a flush=", 100*(flush/10000),"%")

## 8. Functions


### 8.1 Introduction

As the words suggests, *functions* are a piece of code that have a specific function or purpose. As an analogy, if a human is a computer program, then the mind can be considered to be a function, which has purpose of thinking, eyes can be another function, which have a purpose of seeing. These functions are called upon by the human when needed.

Similarly, in case of a computer program, functions are a piece of code, that perform a specific task, when called upon by the program. Instead of being defined as a function, the piece of code can also be used directly whenever it is needed in a program. However, defining a frequently-used piece of code as a function has the following benefits:

1. It reduces the number of lines of code, as the lines of code need to be written just once in the function definition. Thereafter, the function is called by its name, wherever needed in the program. This makes the code compact, and enhances readability.

2. It makes the process of writing code easier, as the user needs to just type the name of the function, wherever it is needed, instead of pasting lines of code.

3. It can be used in different programs, thereby saving time in writing other programs.

To put it more formally, a function is a piece of code that takes arguments (if any) as input, performs computations or tasks, and then returns a result or results.


| **Term**               | **Description**                                                               |
| ---------------------- | ----------------------------------------------------------------------------- |
| `def`                  | The **keyword** used to define a function                                     |
| Function Name          | The **name** you assign to the function (e.g., `greet`, `add_numbers`)        |
| Parameters / Arguments | **Inputs** passed into the function, placed inside parentheses `( )`          |
| Colon `:`              | Indicates the **start of the function body**                                  |
| Function Body          | The **indented block of code** that runs when the function is called          |
| `return` Statement     | Used to **send a value back** to the caller                                   |
| Function Call          | The syntax used to **run/invoke** the function (e.g., `greet("Alice")`)       |
| Docstring (optional)   | A string just below the function header that describes what the function does |

In [105]:
def greet(name):               # def → function definition keyword
    """Say hello to someone.""" # docstring (optional)
    message = "Hello, " + name  # function body
    return message              # return statement

In [106]:
greet("Anna")

'Hello, Anna'

- def is the definition keyword

- greet is the function name

- name is the parameter

- Everything indented is the function body

- return message is the return statement

### 8.2 Defining a function

Look at the function defined below. It asks the user to input a number, and prints whether the number is odd or even.

In [107]:
#This is an example of a function definition

#A function definition begins with the 'def' keyword followed by the name of the function.
#Note that 'odd_even()' is the name of the function below.
def odd_even():
    num = int(input("Enter an integer:"))
    if num%2==0:
        print("Even")
    else:
        print("Odd")   #Function definition ends here

print("This line is not a part of the function as it is not indented") #This line is not a part of the function

This line is not a part of the function as it is not indented

This line is not a part of the function as it is not indented
Note that the function is defined using the `def` keyword. All the lines within the function definition are indented. The indentation shows the lines of code that below to the function. When the indentation stops, the function definition is considered to have ended.

Whenever the user wishes to input a number and print whether it is odd or even, they can call the function defined above by its name as follows:

In [108]:
odd_even()

Enter an integer:8
Even

In Python, empty parentheses are used when defining a function, even if it doesn’t take any parameters. This is a syntactic requirement to differentiate between variables and functions. It helps Python understand that you are defining a function, not just referencing a variable.

### 8.3 Parameters and arguments of a function

Note that the function defined above needs no input when called. However, sometimes we may wish to define a function that takes input(s), and performs computations on the inputs to produce an output. These input(s) are called parameter(s) of a function. When a function is called, the value(s) of these parameter(s) must be specified as argument(s) to the function.

#### 8.3.1 Function with a parameter
Let us change the previous example to write a function that takes an integer as an input argument, and prints whether it is odd or even:

In [109]:
#This is an example of a function definition that has an argument
def odd_even(num):
    if num%2==0:
        print("Even")
    else:
        print("Odd")

In [110]:
odd_even(7)

Odd

We can use the function whenever we wish to find a number is odd or even. For example, if we wish to find that a number input by the user is odd or even, we can call the function with the user input as its argument.

In [ ]:
number = int(input("Enter an integer:"))
odd_even(number)

Note that the above function needs an argument as per the function definition. It will produce an error if called without an argument:

In [ ]:
odd_even()

#### 8.3.2 Function with a parameter having a default value

To avoid errors as above, sometimes is a good idea to assign a default value to the parameter in the function definition:

In [111]:
#This is an example of a function definition that has an argument with a default value
def odd_even(num=8):
    if num%2==0:
        print("Even")
    else:
        print("Odd")

In [113]:
odd_even(9)

Odd

Now, we can call the function without an argument. The function will use the default value of the parameter specified in the function definition.

In [ ]:
odd_even()

### 8.3.3 Function with multiple parameters

A function can have as many parameters as needed. Multiple parameters/arguments are separated by commas. For example, below is a function that inputs two strings, concatenates them with a space in between, and prints the output:

In [114]:
def concat_string(string1, string2):
    print(string1+' '+string2)

In [115]:
concat_string("Hi", "there")

Hi there

### 8.4 Functions that return objects

Until now, we saw functions that print text. However, the functions did not `return` any object. For example, the function `odd_even` prints whether the number is odd or even. However, we did not save this information. In future, we may need to use the information that whether the number was odd or even. Thus, typically, we return an object from the function definition, which consists of the information we may need in the future.

The example `odd_even` can be updated to return the text “odd” or “even” as shown below:

In [116]:
#This is an example of a function definition that has an argument with a default value, and returns an object
def odd_even(num=0):
    if num%2==0:
        return("Even")
    else:
        return("Odd")

The function above returns a string “Odd” or “Even”, depending on whether the number is odd or even. This result can be stored in a variable, which can be used later.

In [117]:
response=odd_even(3)
response

'Odd'

The variable `response` now refers to the object where the string “Odd” or “Even” is stored. Thus, the result of the computation is stored, and the variable can be used later on in the program. Note that the control flow exits the function as soon as the first `return` statement is executed.